version: '2.2'
services:
  robotino:
    image: rustemsuniev/curl-container:latest
    volumes:
      - .:/robotino
    command: /robotino/mobilerobotfleet
    scale: 5
    expose:
      - "2380"
      - "80"
      - "2379"